import Head from 'next/head';
import {
  BsFillMoonStarsFill,
  BsInstagram,
  BsLinkedin,
  BsYoutube,
  BsFacebook
} from 'react-icons/bs';
import Image from 'next/image';
import td from "../public/dev-ed-wave.png"
import design from "../public/design.png"
import code from "../public/code.png"
import consulting from "../public/consulting.png"
import web1 from "../public/web1.png"
import web2 from "../public/web2.png"
import web3 from "../public/web3.png"
import web4 from "../public/web4.png"
import web5 from "../public/web5.png"
import web6 from "../public/web6.png"
import { useState } from 'react';




export default function Home() {
  const [darkMode, setDarkMode] = useState(false);

  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Tshiring D.</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
        <section className='min-h-screen'>
          <nav className='py-10 mb-12 flex justify-between'>
            <h1 className='text-xl font-burtons dark:text-white'>TD</h1>
            <ul className='flex items-center'>
              <li>
                <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl dark:text-white' />
              </li>
              <li>
              <a href="#" className='bg-cyan-500 text-white px-4 py-2 rounded-md ml-8'>Resume</a>
              </li>
            </ul>
          </nav>
          <div className='text-center p-10'>
            <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>Tshiring Dorje Sherpa</h2>
            <h3 className=' text-2xl py-2 md:text-3xl dark:text-white'>Front End Developer</h3>
            <p className='text-md py-5 leading-8 text-gray-800 md:text-xl max-w-lg mx-auto dark:text-white'>
              Developer idk blabla
            </p>
          </div>
          <div className='text-4xl flex justify-center gap-16 py-3 text-gray-600'>
            <a href="https://www.instagram.com/tshiringdorjesherpa/">
              <BsInstagram/>
            </a>
            <a href="https://www.linkedin.com/in/tshiringdorjesherpa/">
              <BsLinkedin/>
            </a>
            <a href="https://www.youtube.com/TshiringDSherpa">
              <BsYoutube/>
            </a>
            <a href="https://www.facebook.com/tshiringdorjesherpa/">
              <BsFacebook/>
            </a>
          </div>
          <div className='relative bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-10 mx-auto overflow-hidden md:h-96 md:w-96'>
            <Image src={td} layout="fill" objectFit='cover'/>
          </div>
        </section>
        {/* second */}
        <section>
          <div>
            <h3 className='text-3xl py-1 dark:text-white dark:text-white'>Services I offer</h3>
            <p className='text-md py-2 leading-6 text-gray-800 dark:text-white dark:text-white'>
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Labore, necessitatibus.
            </p>
          </div>
          <div className='lg:flex gap-10'>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-600'>
              <Image src={design} width={100} height={100}/>
              <h3 className='text-lg font-medium pt-8 pb-2 dark:text-white dark:text-white'>Beautiful Design</h3>
              <p className='py-2 dark:text-white dark:text-white'>
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Illo, doloremque?
              </p>
              <h4 className='py-4 text-teal-600 dark:text-white'>Deisgn tools I use</h4>
              <p className='text-gray-800 py-1 dark:text-white'>PhotoShop</p>
              <p className='text-gray-800 py-1 dark:text-white'>Figma</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-600'>
              <Image src={code} width={100} height={100}/>
              <h3 className='text-lg font-medium pt-8 pb-2 dark:text-white'>Beautiful Design</h3>
              <p className='py-2 dark:text-white'>
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Illo, doloremque?
              </p>
              <h4 className='py-4 text-teal-600 dark:text-white'>Deisgn tools I use</h4>
              <p className='text-gray-800 py-1 dark:text-white'>PhotoShop</p>
              <p className='text-gray-800 py-1 dark:text-white'>Figma</p>
            </div>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-gray-600'>
              <Image src={consulting} width={100} height={100}/>
              <h3 className='text-lg font-medium pt-8 pb-2 dark:text-white'>Beautiful Design</h3>
              <p className='py-2 dark:text-white'>
                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Illo, doloremque?
              </p>
              <h4 className='py-4 text-teal-600c dark:text-white'>Deisgn tools I use</h4>
              <p className='text-gray-800 py-1c dark:text-white'>PhotoShop</p>
              <p className='text-gray-800 py-1c dark:text-white'>Figma</p>
            </div>
          </div>
        </section>
        <section>
          <div>
            <h3 className='text-3xl py-1 dark:text-white'>Portfolio</h3>
            <p className='text-md py-2 leading-6 text-gray-800 dark:text-white'>
              Lorem ipsum dolor sit amet consectetur, adipisicing elit. Labore, necessitatibus.
            </p>
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className='basis-1/3 flex-1'>
              <Image src={web1} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web2} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web3} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web4} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web5} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
            </div>
            <div className='basis-1/3 flex-1'>
              <Image src={web6} className="rounded-lg object-cover" width={'100%'} height={'100%'} layout="responsive"/>
            </div>
          </div>
        </section>
      </main>

      
    </div>
  )
}
